/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApiResponse {
  'status' : ApiStatus,
  'message' : string,
  'timestamp' : Time,
}
export type ApiSource = { 'internetComputerDashboard' : null } |
  { 'icpTokensNet' : null } |
  { 'coinGecko' : null } |
  { 'coinMarketCap' : null };
export interface ApiSourceLog {
  'source' : ApiSource,
  'message' : string,
  'timestamp' : Time,
}
export type ApiStatus = { 'pending' : null } |
  { 'error' : null } |
  { 'success' : null };
export interface ChartDataPoint {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'volume' : number,
  'timestamp' : Time,
}
export interface ChartDataResponse {
  'source' : ApiSource,
  'data' : Array<ChartDataPoint>,
  'timestamp' : Time,
  'priceChange' : PriceChange,
}
export type ChartTimeframe = { 'all' : null } |
  { 'sevenDays' : null } |
  { 'oneYear' : null } |
  { 'threeMonths' : null } |
  { 'oneMonth' : null } |
  { 'sixMonths' : null } |
  { 'oneDay' : null };
export interface CompositePriceData {
  'averagePrice' : number,
  'timestamp' : Time,
  'sources' : Array<PriceSourceData>,
}
export interface ConversionRate { 'date' : string, 'rate' : number }
export interface FileReference { 'hash' : string, 'path' : string }
export interface MetricDataPoint { 'value' : number, 'timestamp' : Time }
export type MetricType = { 'canisterStorage' : null } |
  { 'cycleBurnRate' : null } |
  { 'icpCyclesConversion' : null } |
  { 'transactionsPerSecond' : null } |
  { 'canisterCount' : null } |
  { 'subnetCount' : null } |
  { 'nodeProviderCount' : null } |
  { 'nodeMachineCount' : null };
export interface OrderBookData {
  'asks' : Array<OrderBookEntry>,
  'bids' : Array<OrderBookEntry>,
  'timestamp' : Time,
}
export interface OrderBookEntry {
  'source' : ApiSource,
  'timestamp' : Time,
  'price' : number,
  'amount' : number,
}
export interface PriceChange { 'timeframe' : string, 'percentage' : number }
export interface PriceSourceData {
  'source' : ApiSource,
  'timestamp' : Time,
  'price' : number,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserPreferences {
  'customLogoPath' : [] | [string],
  'customAppName' : [] | [string],
  'dayMode' : boolean,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'clearApiSourceLogs' : ActorMethod<[string], undefined>,
  'clearApiStatus' : ActorMethod<[string], undefined>,
  'clearChartData' : ActorMethod<[ChartTimeframe], undefined>,
  'clearCompositePriceData' : ActorMethod<[], undefined>,
  'clearConversionRate' : ActorMethod<[string], undefined>,
  'clearMetricData' : ActorMethod<[MetricType], undefined>,
  'clearOrderBookData' : ActorMethod<[ApiSource], undefined>,
  'clearPriceChange' : ActorMethod<[string], undefined>,
  'clearPriceData' : ActorMethod<[ApiSource], undefined>,
  'clearUserPreferences' : ActorMethod<[string], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'fetchChartDataFromCoinGecko' : ActorMethod<
    [ChartTimeframe],
    ChartDataResponse
  >,
  'fetchChartDataFromCoinMarketCap' : ActorMethod<
    [ChartTimeframe],
    ChartDataResponse
  >,
  'fetchChartDataFromICDashboard' : ActorMethod<
    [ChartTimeframe],
    ChartDataResponse
  >,
  'fetchChartDataFromICPTokensNet' : ActorMethod<
    [ChartTimeframe],
    ChartDataResponse
  >,
  'fetchChartDataWithFallback' : ActorMethod<
    [ChartTimeframe],
    ChartDataResponse
  >,
  'getAllApiStatuses' : ActorMethod<[], Array<ApiResponse>>,
  'getAllChartTimeframes' : ActorMethod<[], Array<string>>,
  'getAllConversionRates' : ActorMethod<[], Array<ConversionRate>>,
  'getAllMetricTypes' : ActorMethod<[], Array<string>>,
  'getAllOrderBookData' : ActorMethod<[], Array<OrderBookData>>,
  'getAllPriceChanges' : ActorMethod<[], Array<PriceChange>>,
  'getAllPriceData' : ActorMethod<[], Array<PriceSourceData>>,
  'getApiSourceLogs' : ActorMethod<[string], Array<ApiSourceLog>>,
  'getApiStatus' : ActorMethod<[string], [] | [ApiResponse]>,
  'getChartData' : ActorMethod<[ChartTimeframe], Array<ChartDataPoint>>,
  'getCompositePriceData' : ActorMethod<[], [] | [CompositePriceData]>,
  'getConversionRate' : ActorMethod<[string], [] | [ConversionRate]>,
  'getDefaultLogoPath' : ActorMethod<[], string>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getHistoricalData' : ActorMethod<[MetricType], Array<MetricDataPoint>>,
  'getLastUpdated' : ActorMethod<[], Time>,
  'getOrderBookData' : ActorMethod<[ApiSource], [] | [OrderBookData]>,
  'getPriceChange' : ActorMethod<[string], [] | [PriceChange]>,
  'getPriceData' : ActorMethod<[ApiSource], [] | [PriceSourceData]>,
  'getUserPreferences' : ActorMethod<[string], [] | [UserPreferences]>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'logApiSource' : ActorMethod<[string, ApiSource, string], undefined>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'setDefaultLogoPath' : ActorMethod<[string], undefined>,
  'setUserPreferences' : ActorMethod<
    [string, boolean, [] | [string], [] | [string]],
    undefined
  >,
  'storeApiStatus' : ActorMethod<[string, ApiStatus, string], undefined>,
  'storeChartData' : ActorMethod<
    [ChartTimeframe, Array<ChartDataPoint>],
    undefined
  >,
  'storeCompositePriceData' : ActorMethod<
    [number, Array<PriceSourceData>],
    undefined
  >,
  'storeConversionRate' : ActorMethod<[string, number], undefined>,
  'storeMetricData' : ActorMethod<[MetricType, number], undefined>,
  'storeOrderBookData' : ActorMethod<
    [ApiSource, Array<OrderBookEntry>, Array<OrderBookEntry>],
    undefined
  >,
  'storePriceChange' : ActorMethod<[string, number], undefined>,
  'storePriceData' : ActorMethod<[ApiSource, number], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];