/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChartTimeframe = IDL.Variant({
  'all' : IDL.Null,
  'sevenDays' : IDL.Null,
  'oneYear' : IDL.Null,
  'threeMonths' : IDL.Null,
  'oneMonth' : IDL.Null,
  'sixMonths' : IDL.Null,
  'oneDay' : IDL.Null,
});
export const MetricType = IDL.Variant({
  'canisterStorage' : IDL.Null,
  'cycleBurnRate' : IDL.Null,
  'icpCyclesConversion' : IDL.Null,
  'transactionsPerSecond' : IDL.Null,
  'canisterCount' : IDL.Null,
  'subnetCount' : IDL.Null,
  'nodeProviderCount' : IDL.Null,
  'nodeMachineCount' : IDL.Null,
});
export const ApiSource = IDL.Variant({
  'internetComputerDashboard' : IDL.Null,
  'icpTokensNet' : IDL.Null,
  'coinGecko' : IDL.Null,
  'coinMarketCap' : IDL.Null,
});
export const Time = IDL.Int;
export const ChartDataPoint = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'volume' : IDL.Float64,
  'timestamp' : Time,
});
export const PriceChange = IDL.Record({
  'timeframe' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const ChartDataResponse = IDL.Record({
  'source' : ApiSource,
  'data' : IDL.Vec(ChartDataPoint),
  'timestamp' : Time,
  'priceChange' : PriceChange,
});
export const ApiStatus = IDL.Variant({
  'pending' : IDL.Null,
  'error' : IDL.Null,
  'success' : IDL.Null,
});
export const ApiResponse = IDL.Record({
  'status' : ApiStatus,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ConversionRate = IDL.Record({
  'date' : IDL.Text,
  'rate' : IDL.Float64,
});
export const OrderBookEntry = IDL.Record({
  'source' : ApiSource,
  'timestamp' : Time,
  'price' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const OrderBookData = IDL.Record({
  'asks' : IDL.Vec(OrderBookEntry),
  'bids' : IDL.Vec(OrderBookEntry),
  'timestamp' : Time,
});
export const PriceSourceData = IDL.Record({
  'source' : ApiSource,
  'timestamp' : Time,
  'price' : IDL.Float64,
});
export const ApiSourceLog = IDL.Record({
  'source' : ApiSource,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const CompositePriceData = IDL.Record({
  'averagePrice' : IDL.Float64,
  'timestamp' : Time,
  'sources' : IDL.Vec(PriceSourceData),
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const MetricDataPoint = IDL.Record({
  'value' : IDL.Float64,
  'timestamp' : Time,
});
export const UserPreferences = IDL.Record({
  'customLogoPath' : IDL.Opt(IDL.Text),
  'customAppName' : IDL.Opt(IDL.Text),
  'dayMode' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'clearApiSourceLogs' : IDL.Func([IDL.Text], [], []),
  'clearApiStatus' : IDL.Func([IDL.Text], [], []),
  'clearChartData' : IDL.Func([ChartTimeframe], [], []),
  'clearCompositePriceData' : IDL.Func([], [], []),
  'clearConversionRate' : IDL.Func([IDL.Text], [], []),
  'clearMetricData' : IDL.Func([MetricType], [], []),
  'clearOrderBookData' : IDL.Func([ApiSource], [], []),
  'clearPriceChange' : IDL.Func([IDL.Text], [], []),
  'clearPriceData' : IDL.Func([ApiSource], [], []),
  'clearUserPreferences' : IDL.Func([IDL.Text], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'fetchChartDataFromCoinGecko' : IDL.Func(
      [ChartTimeframe],
      [ChartDataResponse],
      [],
    ),
  'fetchChartDataFromCoinMarketCap' : IDL.Func(
      [ChartTimeframe],
      [ChartDataResponse],
      [],
    ),
  'fetchChartDataFromICDashboard' : IDL.Func(
      [ChartTimeframe],
      [ChartDataResponse],
      [],
    ),
  'fetchChartDataFromICPTokensNet' : IDL.Func(
      [ChartTimeframe],
      [ChartDataResponse],
      [],
    ),
  'fetchChartDataWithFallback' : IDL.Func(
      [ChartTimeframe],
      [ChartDataResponse],
      [],
    ),
  'getAllApiStatuses' : IDL.Func([], [IDL.Vec(ApiResponse)], ['query']),
  'getAllChartTimeframes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllConversionRates' : IDL.Func([], [IDL.Vec(ConversionRate)], ['query']),
  'getAllMetricTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllOrderBookData' : IDL.Func([], [IDL.Vec(OrderBookData)], ['query']),
  'getAllPriceChanges' : IDL.Func([], [IDL.Vec(PriceChange)], ['query']),
  'getAllPriceData' : IDL.Func([], [IDL.Vec(PriceSourceData)], ['query']),
  'getApiSourceLogs' : IDL.Func([IDL.Text], [IDL.Vec(ApiSourceLog)], ['query']),
  'getApiStatus' : IDL.Func([IDL.Text], [IDL.Opt(ApiResponse)], ['query']),
  'getChartData' : IDL.Func(
      [ChartTimeframe],
      [IDL.Vec(ChartDataPoint)],
      ['query'],
    ),
  'getCompositePriceData' : IDL.Func(
      [],
      [IDL.Opt(CompositePriceData)],
      ['query'],
    ),
  'getConversionRate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ConversionRate)],
      ['query'],
    ),
  'getDefaultLogoPath' : IDL.Func([], [IDL.Text], ['query']),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getHistoricalData' : IDL.Func(
      [MetricType],
      [IDL.Vec(MetricDataPoint)],
      ['query'],
    ),
  'getLastUpdated' : IDL.Func([], [Time], ['query']),
  'getOrderBookData' : IDL.Func(
      [ApiSource],
      [IDL.Opt(OrderBookData)],
      ['query'],
    ),
  'getPriceChange' : IDL.Func([IDL.Text], [IDL.Opt(PriceChange)], ['query']),
  'getPriceData' : IDL.Func([ApiSource], [IDL.Opt(PriceSourceData)], ['query']),
  'getUserPreferences' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserPreferences)],
      ['query'],
    ),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'logApiSource' : IDL.Func([IDL.Text, ApiSource, IDL.Text], [], []),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setDefaultLogoPath' : IDL.Func([IDL.Text], [], []),
  'setUserPreferences' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'storeApiStatus' : IDL.Func([IDL.Text, ApiStatus, IDL.Text], [], []),
  'storeChartData' : IDL.Func(
      [ChartTimeframe, IDL.Vec(ChartDataPoint)],
      [],
      [],
    ),
  'storeCompositePriceData' : IDL.Func(
      [IDL.Float64, IDL.Vec(PriceSourceData)],
      [],
      [],
    ),
  'storeConversionRate' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'storeMetricData' : IDL.Func([MetricType, IDL.Float64], [], []),
  'storeOrderBookData' : IDL.Func(
      [ApiSource, IDL.Vec(OrderBookEntry), IDL.Vec(OrderBookEntry)],
      [],
      [],
    ),
  'storePriceChange' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'storePriceData' : IDL.Func([ApiSource, IDL.Float64], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChartTimeframe = IDL.Variant({
    'all' : IDL.Null,
    'sevenDays' : IDL.Null,
    'oneYear' : IDL.Null,
    'threeMonths' : IDL.Null,
    'oneMonth' : IDL.Null,
    'sixMonths' : IDL.Null,
    'oneDay' : IDL.Null,
  });
  const MetricType = IDL.Variant({
    'canisterStorage' : IDL.Null,
    'cycleBurnRate' : IDL.Null,
    'icpCyclesConversion' : IDL.Null,
    'transactionsPerSecond' : IDL.Null,
    'canisterCount' : IDL.Null,
    'subnetCount' : IDL.Null,
    'nodeProviderCount' : IDL.Null,
    'nodeMachineCount' : IDL.Null,
  });
  const ApiSource = IDL.Variant({
    'internetComputerDashboard' : IDL.Null,
    'icpTokensNet' : IDL.Null,
    'coinGecko' : IDL.Null,
    'coinMarketCap' : IDL.Null,
  });
  const Time = IDL.Int;
  const ChartDataPoint = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'volume' : IDL.Float64,
    'timestamp' : Time,
  });
  const PriceChange = IDL.Record({
    'timeframe' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const ChartDataResponse = IDL.Record({
    'source' : ApiSource,
    'data' : IDL.Vec(ChartDataPoint),
    'timestamp' : Time,
    'priceChange' : PriceChange,
  });
  const ApiStatus = IDL.Variant({
    'pending' : IDL.Null,
    'error' : IDL.Null,
    'success' : IDL.Null,
  });
  const ApiResponse = IDL.Record({
    'status' : ApiStatus,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ConversionRate = IDL.Record({
    'date' : IDL.Text,
    'rate' : IDL.Float64,
  });
  const OrderBookEntry = IDL.Record({
    'source' : ApiSource,
    'timestamp' : Time,
    'price' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const OrderBookData = IDL.Record({
    'asks' : IDL.Vec(OrderBookEntry),
    'bids' : IDL.Vec(OrderBookEntry),
    'timestamp' : Time,
  });
  const PriceSourceData = IDL.Record({
    'source' : ApiSource,
    'timestamp' : Time,
    'price' : IDL.Float64,
  });
  const ApiSourceLog = IDL.Record({
    'source' : ApiSource,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const CompositePriceData = IDL.Record({
    'averagePrice' : IDL.Float64,
    'timestamp' : Time,
    'sources' : IDL.Vec(PriceSourceData),
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const MetricDataPoint = IDL.Record({
    'value' : IDL.Float64,
    'timestamp' : Time,
  });
  const UserPreferences = IDL.Record({
    'customLogoPath' : IDL.Opt(IDL.Text),
    'customAppName' : IDL.Opt(IDL.Text),
    'dayMode' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'clearApiSourceLogs' : IDL.Func([IDL.Text], [], []),
    'clearApiStatus' : IDL.Func([IDL.Text], [], []),
    'clearChartData' : IDL.Func([ChartTimeframe], [], []),
    'clearCompositePriceData' : IDL.Func([], [], []),
    'clearConversionRate' : IDL.Func([IDL.Text], [], []),
    'clearMetricData' : IDL.Func([MetricType], [], []),
    'clearOrderBookData' : IDL.Func([ApiSource], [], []),
    'clearPriceChange' : IDL.Func([IDL.Text], [], []),
    'clearPriceData' : IDL.Func([ApiSource], [], []),
    'clearUserPreferences' : IDL.Func([IDL.Text], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'fetchChartDataFromCoinGecko' : IDL.Func(
        [ChartTimeframe],
        [ChartDataResponse],
        [],
      ),
    'fetchChartDataFromCoinMarketCap' : IDL.Func(
        [ChartTimeframe],
        [ChartDataResponse],
        [],
      ),
    'fetchChartDataFromICDashboard' : IDL.Func(
        [ChartTimeframe],
        [ChartDataResponse],
        [],
      ),
    'fetchChartDataFromICPTokensNet' : IDL.Func(
        [ChartTimeframe],
        [ChartDataResponse],
        [],
      ),
    'fetchChartDataWithFallback' : IDL.Func(
        [ChartTimeframe],
        [ChartDataResponse],
        [],
      ),
    'getAllApiStatuses' : IDL.Func([], [IDL.Vec(ApiResponse)], ['query']),
    'getAllChartTimeframes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllConversionRates' : IDL.Func(
        [],
        [IDL.Vec(ConversionRate)],
        ['query'],
      ),
    'getAllMetricTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllOrderBookData' : IDL.Func([], [IDL.Vec(OrderBookData)], ['query']),
    'getAllPriceChanges' : IDL.Func([], [IDL.Vec(PriceChange)], ['query']),
    'getAllPriceData' : IDL.Func([], [IDL.Vec(PriceSourceData)], ['query']),
    'getApiSourceLogs' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ApiSourceLog)],
        ['query'],
      ),
    'getApiStatus' : IDL.Func([IDL.Text], [IDL.Opt(ApiResponse)], ['query']),
    'getChartData' : IDL.Func(
        [ChartTimeframe],
        [IDL.Vec(ChartDataPoint)],
        ['query'],
      ),
    'getCompositePriceData' : IDL.Func(
        [],
        [IDL.Opt(CompositePriceData)],
        ['query'],
      ),
    'getConversionRate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ConversionRate)],
        ['query'],
      ),
    'getDefaultLogoPath' : IDL.Func([], [IDL.Text], ['query']),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getHistoricalData' : IDL.Func(
        [MetricType],
        [IDL.Vec(MetricDataPoint)],
        ['query'],
      ),
    'getLastUpdated' : IDL.Func([], [Time], ['query']),
    'getOrderBookData' : IDL.Func(
        [ApiSource],
        [IDL.Opt(OrderBookData)],
        ['query'],
      ),
    'getPriceChange' : IDL.Func([IDL.Text], [IDL.Opt(PriceChange)], ['query']),
    'getPriceData' : IDL.Func(
        [ApiSource],
        [IDL.Opt(PriceSourceData)],
        ['query'],
      ),
    'getUserPreferences' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserPreferences)],
        ['query'],
      ),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'logApiSource' : IDL.Func([IDL.Text, ApiSource, IDL.Text], [], []),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setDefaultLogoPath' : IDL.Func([IDL.Text], [], []),
    'setUserPreferences' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'storeApiStatus' : IDL.Func([IDL.Text, ApiStatus, IDL.Text], [], []),
    'storeChartData' : IDL.Func(
        [ChartTimeframe, IDL.Vec(ChartDataPoint)],
        [],
        [],
      ),
    'storeCompositePriceData' : IDL.Func(
        [IDL.Float64, IDL.Vec(PriceSourceData)],
        [],
        [],
      ),
    'storeConversionRate' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'storeMetricData' : IDL.Func([MetricType, IDL.Float64], [], []),
    'storeOrderBookData' : IDL.Func(
        [ApiSource, IDL.Vec(OrderBookEntry), IDL.Vec(OrderBookEntry)],
        [],
        [],
      ),
    'storePriceChange' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'storePriceData' : IDL.Func([ApiSource, IDL.Float64], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };