/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserPreferences {
    customLogoPath?: string;
    customAppName?: string;
    dayMode: boolean;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PriceChange {
    timeframe: string;
    percentage: number;
}
export interface ChartDataResponse {
    source: ApiSource;
    data: Array<ChartDataPoint>;
    timestamp: Time;
    priceChange: PriceChange;
}
export interface ApiResponse {
    status: ApiStatus;
    message: string;
    timestamp: Time;
}
export interface MetricDataPoint {
    value: number;
    timestamp: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface OrderBookEntry {
    source: ApiSource;
    timestamp: Time;
    price: number;
    amount: number;
}
export interface ChartDataPoint {
    low: number;
    high: number;
    close: number;
    open: number;
    volume: number;
    timestamp: Time;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface OrderBookData {
    asks: Array<OrderBookEntry>;
    bids: Array<OrderBookEntry>;
    timestamp: Time;
}
export interface ApiSourceLog {
    source: ApiSource;
    message: string;
    timestamp: Time;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PriceSourceData {
    source: ApiSource;
    timestamp: Time;
    price: number;
}
export interface CompositePriceData {
    averagePrice: number;
    timestamp: Time;
    sources: Array<PriceSourceData>;
}
export interface ConversionRate {
    date: string;
    rate: number;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApiSource {
    internetComputerDashboard = "internetComputerDashboard",
    icpTokensNet = "icpTokensNet",
    coinGecko = "coinGecko",
    coinMarketCap = "coinMarketCap"
}
export enum ApiStatus {
    pending = "pending",
    error = "error",
    success = "success"
}
export enum ChartTimeframe {
    fourHours = "fourHours",
    oneHour = "oneHour",
    sevenDays = "sevenDays",
    oneYear = "oneYear",
    eightHours = "eightHours",
    fifteenMinutes = "fifteenMinutes",
    oneMonth = "oneMonth",
    oneDay = "oneDay"
}
export enum MetricType {
    canisterStorage = "canisterStorage",
    cycleBurnRate = "cycleBurnRate",
    icpCyclesConversion = "icpCyclesConversion",
    transactionsPerSecond = "transactionsPerSecond",
    canisterCount = "canisterCount",
    subnetCount = "subnetCount",
    nodeProviderCount = "nodeProviderCount",
    nodeMachineCount = "nodeMachineCount"
}
export interface backendInterface {
    _caffeineStorageBlobsToDelete(): Promise<Array<string>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<string>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    clearApiSourceLogs(apiName: string): Promise<void>;
    clearApiStatus(apiName: string): Promise<void>;
    clearChartData(timeframe: ChartTimeframe): Promise<void>;
    clearCompositePriceData(): Promise<void>;
    clearConversionRate(date: string): Promise<void>;
    clearMetricData(metricType: MetricType): Promise<void>;
    clearOrderBookData(source: ApiSource): Promise<void>;
    clearPriceChange(timeframe: string): Promise<void>;
    clearPriceData(source: ApiSource): Promise<void>;
    clearUserPreferences(userId: string): Promise<void>;
    fetchChartDataFromCoinGecko(timeframe: ChartTimeframe): Promise<ChartDataResponse>;
    fetchChartDataFromCoinMarketCap(timeframe: ChartTimeframe): Promise<ChartDataResponse>;
    fetchChartDataFromICDashboard(timeframe: ChartTimeframe): Promise<ChartDataResponse>;
    fetchChartDataFromICPTokensNet(timeframe: ChartTimeframe): Promise<ChartDataResponse>;
    fetchChartDataWithFallback(timeframe: ChartTimeframe): Promise<ChartDataResponse>;
    getAllApiStatuses(): Promise<Array<ApiResponse>>;
    getAllChartTimeframes(): Promise<Array<string>>;
    getAllConversionRates(): Promise<Array<ConversionRate>>;
    getAllMetricTypes(): Promise<Array<string>>;
    getAllOrderBookData(): Promise<Array<OrderBookData>>;
    getAllPriceChanges(): Promise<Array<PriceChange>>;
    getAllPriceData(): Promise<Array<PriceSourceData>>;
    getApiSourceLogs(apiName: string): Promise<Array<ApiSourceLog>>;
    getApiStatus(apiName: string): Promise<ApiResponse | null>;
    getChartData(timeframe: ChartTimeframe): Promise<Array<ChartDataPoint>>;
    getCompositePriceData(): Promise<CompositePriceData | null>;
    getConversionRate(date: string): Promise<ConversionRate | null>;
    getDefaultLogoPath(): Promise<string>;
    getHistoricalData(metricType: MetricType): Promise<Array<MetricDataPoint>>;
    getLastUpdated(): Promise<Time>;
    getOrderBookData(source: ApiSource): Promise<OrderBookData | null>;
    getPriceChange(timeframe: string): Promise<PriceChange | null>;
    getPriceData(source: ApiSource): Promise<PriceSourceData | null>;
    getUserPreferences(userId: string): Promise<UserPreferences | null>;
    logApiSource(apiName: string, source: ApiSource, message: string): Promise<void>;
    setDefaultLogoPath(path: string): Promise<void>;
    setUserPreferences(userId: string, dayMode: boolean, customAppName: string | null, customLogoPath: string | null): Promise<void>;
    storeApiStatus(apiName: string, status: ApiStatus, message: string): Promise<void>;
    storeChartData(timeframe: ChartTimeframe, data: Array<ChartDataPoint>): Promise<void>;
    storeCompositePriceData(averagePrice: number, sources: Array<PriceSourceData>): Promise<void>;
    storeConversionRate(date: string, rate: number): Promise<void>;
    storeMetricData(metricType: MetricType, value: number): Promise<void>;
    storeOrderBookData(source: ApiSource, bids: Array<OrderBookEntry>, asks: Array<OrderBookEntry>): Promise<void>;
    storePriceChange(timeframe: string, percentage: number): Promise<void>;
    storePriceData(source: ApiSource, price: number): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { ApiResponse as _ApiResponse, ApiSource as _ApiSource, ApiSourceLog as _ApiSourceLog, ApiStatus as _ApiStatus, ChartDataPoint as _ChartDataPoint, ChartDataResponse as _ChartDataResponse, ChartTimeframe as _ChartTimeframe, CompositePriceData as _CompositePriceData, ConversionRate as _ConversionRate, MetricType as _MetricType, OrderBookData as _OrderBookData, OrderBookEntry as _OrderBookEntry, PriceChange as _PriceChange, PriceSourceData as _PriceSourceData, Time as _Time, UserPreferences as _UserPreferences, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobsToDelete(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async clearApiSourceLogs(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearApiSourceLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearApiSourceLogs(arg0);
            return result;
        }
    }
    async clearApiStatus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearApiStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearApiStatus(arg0);
            return result;
        }
    }
    async clearChartData(arg0: ChartTimeframe): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChartData(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChartData(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async clearCompositePriceData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCompositePriceData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCompositePriceData();
            return result;
        }
    }
    async clearConversionRate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearConversionRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearConversionRate(arg0);
            return result;
        }
    }
    async clearMetricData(arg0: MetricType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMetricData(to_candid_MetricType_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMetricData(to_candid_MetricType_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async clearOrderBookData(arg0: ApiSource): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearOrderBookData(to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearOrderBookData(to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async clearPriceChange(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPriceChange(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPriceChange(arg0);
            return result;
        }
    }
    async clearPriceData(arg0: ApiSource): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPriceData(to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPriceData(to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async clearUserPreferences(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearUserPreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearUserPreferences(arg0);
            return result;
        }
    }
    async fetchChartDataFromCoinGecko(arg0: ChartTimeframe): Promise<ChartDataResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchChartDataFromCoinGecko(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ChartDataResponse_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchChartDataFromCoinGecko(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ChartDataResponse_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchChartDataFromCoinMarketCap(arg0: ChartTimeframe): Promise<ChartDataResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchChartDataFromCoinMarketCap(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ChartDataResponse_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchChartDataFromCoinMarketCap(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ChartDataResponse_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchChartDataFromICDashboard(arg0: ChartTimeframe): Promise<ChartDataResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchChartDataFromICDashboard(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ChartDataResponse_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchChartDataFromICDashboard(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ChartDataResponse_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchChartDataFromICPTokensNet(arg0: ChartTimeframe): Promise<ChartDataResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchChartDataFromICPTokensNet(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ChartDataResponse_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchChartDataFromICPTokensNet(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ChartDataResponse_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchChartDataWithFallback(arg0: ChartTimeframe): Promise<ChartDataResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchChartDataWithFallback(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ChartDataResponse_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchChartDataWithFallback(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ChartDataResponse_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllApiStatuses(): Promise<Array<ApiResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApiStatuses();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApiStatuses();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllChartTimeframes(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChartTimeframes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChartTimeframes();
            return result;
        }
    }
    async getAllConversionRates(): Promise<Array<ConversionRate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConversionRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConversionRates();
            return result;
        }
    }
    async getAllMetricTypes(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMetricTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMetricTypes();
            return result;
        }
    }
    async getAllOrderBookData(): Promise<Array<OrderBookData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrderBookData();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrderBookData();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPriceChanges(): Promise<Array<PriceChange>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPriceChanges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPriceChanges();
            return result;
        }
    }
    async getAllPriceData(): Promise<Array<PriceSourceData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPriceData();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPriceData();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiSourceLogs(arg0: string): Promise<Array<ApiSourceLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiSourceLogs(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiSourceLogs(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiStatus(arg0: string): Promise<ApiResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiStatus(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiStatus(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChartData(arg0: ChartTimeframe): Promise<Array<ChartDataPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChartData(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChartData(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCompositePriceData(): Promise<CompositePriceData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompositePriceData();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompositePriceData();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversionRate(arg0: string): Promise<ConversionRate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversionRate(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversionRate(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDefaultLogoPath(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultLogoPath();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultLogoPath();
            return result;
        }
    }
    async getHistoricalData(arg0: MetricType): Promise<Array<MetricDataPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoricalData(to_candid_MetricType_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoricalData(to_candid_MetricType_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getLastUpdated(): Promise<Time> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastUpdated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastUpdated();
            return result;
        }
    }
    async getOrderBookData(arg0: ApiSource): Promise<OrderBookData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderBookData(to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderBookData(to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriceChange(arg0: string): Promise<PriceChange | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriceChange(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriceChange(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriceData(arg0: ApiSource): Promise<PriceSourceData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriceData(to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriceData(to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPreferences(arg0: string): Promise<UserPreferences | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPreferences(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPreferences(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async logApiSource(arg0: string, arg1: ApiSource, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logApiSource(arg0, to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logApiSource(arg0, to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async setDefaultLogoPath(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDefaultLogoPath(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDefaultLogoPath(arg0);
            return result;
        }
    }
    async setUserPreferences(arg0: string, arg1: boolean, arg2: string | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserPreferences(arg0, arg1, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n47(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserPreferences(arg0, arg1, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n47(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async storeApiStatus(arg0: string, arg1: ApiStatus, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeApiStatus(arg0, to_candid_ApiStatus_n48(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeApiStatus(arg0, to_candid_ApiStatus_n48(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async storeChartData(arg0: ChartTimeframe, arg1: Array<ChartDataPoint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeChartData(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeChartData(to_candid_ChartTimeframe_n8(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async storeCompositePriceData(arg0: number, arg1: Array<PriceSourceData>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeCompositePriceData(arg0, to_candid_vec_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeCompositePriceData(arg0, to_candid_vec_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async storeConversionRate(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeConversionRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeConversionRate(arg0, arg1);
            return result;
        }
    }
    async storeMetricData(arg0: MetricType, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeMetricData(to_candid_MetricType_n10(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeMetricData(to_candid_MetricType_n10(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async storeOrderBookData(arg0: ApiSource, arg1: Array<OrderBookEntry>, arg2: Array<OrderBookEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeOrderBookData(to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg0), to_candid_vec_n53(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n53(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeOrderBookData(to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg0), to_candid_vec_n53(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n53(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async storePriceChange(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storePriceChange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storePriceChange(arg0, arg1);
            return result;
        }
    }
    async storePriceData(arg0: ApiSource, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storePriceData(to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storePriceData(to_candid_ApiSource_n12(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_ApiResponse_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResponse): ApiResponse {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ApiSourceLog_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiSourceLog): ApiSourceLog {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ApiSource_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiSource): ApiSource {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ApiStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiStatus): ApiStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ChartDataResponse_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChartDataResponse): ChartDataResponse {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_CompositePriceData_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompositePriceData): CompositePriceData {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_OrderBookData_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderBookData): OrderBookData {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_OrderBookEntry_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderBookEntry): OrderBookEntry {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_PriceSourceData_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceSourceData): PriceSourceData {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserPreferences_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPreferences): UserPreferences {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApiResponse]): ApiResponse | null {
    return value.length === 0 ? null : from_candid_ApiResponse_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompositePriceData]): CompositePriceData | null {
    return value.length === 0 ? null : from_candid_CompositePriceData_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ConversionRate]): ConversionRate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderBookData]): OrderBookData | null {
    return value.length === 0 ? null : from_candid_OrderBookData_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PriceChange]): PriceChange | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PriceSourceData]): PriceSourceData | null {
    return value.length === 0 ? null : from_candid_PriceSourceData_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPreferences]): UserPreferences | null {
    return value.length === 0 ? null : from_candid_UserPreferences_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: _ApiSource;
    data: Array<_ChartDataPoint>;
    timestamp: _Time;
    priceChange: _PriceChange;
}): {
    source: ApiSource;
    data: Array<ChartDataPoint>;
    timestamp: Time;
    priceChange: PriceChange;
} {
    return {
        source: from_candid_ApiSource_n16(_uploadFile, _downloadFile, value.source),
        data: value.data,
        timestamp: value.timestamp,
        priceChange: value.priceChange
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApiStatus;
    message: string;
    timestamp: _Time;
}): {
    status: ApiStatus;
    message: string;
    timestamp: Time;
} {
    return {
        status: from_candid_ApiStatus_n21(_uploadFile, _downloadFile, value.status),
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    asks: Array<_OrderBookEntry>;
    bids: Array<_OrderBookEntry>;
    timestamp: _Time;
}): {
    asks: Array<OrderBookEntry>;
    bids: Array<OrderBookEntry>;
    timestamp: Time;
} {
    return {
        asks: from_candid_vec_n26(_uploadFile, _downloadFile, value.asks),
        bids: from_candid_vec_n26(_uploadFile, _downloadFile, value.bids),
        timestamp: value.timestamp
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: _ApiSource;
    timestamp: _Time;
    price: number;
    amount: number;
}): {
    source: ApiSource;
    timestamp: Time;
    price: number;
    amount: number;
} {
    return {
        source: from_candid_ApiSource_n16(_uploadFile, _downloadFile, value.source),
        timestamp: value.timestamp,
        price: value.price,
        amount: value.amount
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: _ApiSource;
    timestamp: _Time;
    price: number;
}): {
    source: ApiSource;
    timestamp: Time;
    price: number;
} {
    return {
        source: from_candid_ApiSource_n16(_uploadFile, _downloadFile, value.source),
        timestamp: value.timestamp,
        price: value.price
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: _ApiSource;
    message: string;
    timestamp: _Time;
}): {
    source: ApiSource;
    message: string;
    timestamp: Time;
} {
    return {
        source: from_candid_ApiSource_n16(_uploadFile, _downloadFile, value.source),
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averagePrice: number;
    timestamp: _Time;
    sources: Array<_PriceSourceData>;
}): {
    averagePrice: number;
    timestamp: Time;
    sources: Array<PriceSourceData>;
} {
    return {
        averagePrice: value.averagePrice,
        timestamp: value.timestamp,
        sources: from_candid_vec_n29(_uploadFile, _downloadFile, value.sources)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customLogoPath: [] | [string];
    customAppName: [] | [string];
    dayMode: boolean;
}): {
    customLogoPath?: string;
    customAppName?: string;
    dayMode: boolean;
} {
    return {
        customLogoPath: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.customLogoPath)),
        customAppName: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.customAppName)),
        dayMode: value.dayMode
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internetComputerDashboard: null;
} | {
    icpTokensNet: null;
} | {
    coinGecko: null;
} | {
    coinMarketCap: null;
}): ApiSource {
    return "internetComputerDashboard" in value ? ApiSource.internetComputerDashboard : "icpTokensNet" in value ? ApiSource.icpTokensNet : "coinGecko" in value ? ApiSource.coinGecko : "coinMarketCap" in value ? ApiSource.coinMarketCap : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    error: null;
} | {
    success: null;
}): ApiStatus {
    return "pending" in value ? ApiStatus.pending : "error" in value ? ApiStatus.error : "success" in value ? ApiStatus.success : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApiResponse>): Array<ApiResponse> {
    return value.map((x)=>from_candid_ApiResponse_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderBookData>): Array<OrderBookData> {
    return value.map((x)=>from_candid_OrderBookData_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderBookEntry>): Array<OrderBookEntry> {
    return value.map((x)=>from_candid_OrderBookEntry_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PriceSourceData>): Array<PriceSourceData> {
    return value.map((x)=>from_candid_PriceSourceData_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApiSourceLog>): Array<ApiSourceLog> {
    return value.map((x)=>from_candid_ApiSourceLog_n33(_uploadFile, _downloadFile, x));
}
function to_candid_ApiSource_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApiSource): _ApiSource {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ApiStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApiStatus): _ApiStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_ChartTimeframe_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChartTimeframe): _ChartTimeframe {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_MetricType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MetricType): _MetricType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_OrderBookEntry_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderBookEntry): _OrderBookEntry {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_PriceSourceData_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceSourceData): _PriceSourceData {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: ApiSource;
    timestamp: Time;
    price: number;
}): {
    source: _ApiSource;
    timestamp: _Time;
    price: number;
} {
    return {
        source: to_candid_ApiSource_n12(_uploadFile, _downloadFile, value.source),
        timestamp: value.timestamp,
        price: value.price
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: ApiSource;
    timestamp: Time;
    price: number;
    amount: number;
}): {
    source: _ApiSource;
    timestamp: _Time;
    price: number;
    amount: number;
} {
    return {
        source: to_candid_ApiSource_n12(_uploadFile, _downloadFile, value.source),
        timestamp: value.timestamp,
        price: value.price,
        amount: value.amount
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MetricType): {
    canisterStorage: null;
} | {
    cycleBurnRate: null;
} | {
    icpCyclesConversion: null;
} | {
    transactionsPerSecond: null;
} | {
    canisterCount: null;
} | {
    subnetCount: null;
} | {
    nodeProviderCount: null;
} | {
    nodeMachineCount: null;
} {
    return value == MetricType.canisterStorage ? {
        canisterStorage: null
    } : value == MetricType.cycleBurnRate ? {
        cycleBurnRate: null
    } : value == MetricType.icpCyclesConversion ? {
        icpCyclesConversion: null
    } : value == MetricType.transactionsPerSecond ? {
        transactionsPerSecond: null
    } : value == MetricType.canisterCount ? {
        canisterCount: null
    } : value == MetricType.subnetCount ? {
        subnetCount: null
    } : value == MetricType.nodeProviderCount ? {
        nodeProviderCount: null
    } : value == MetricType.nodeMachineCount ? {
        nodeMachineCount: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApiSource): {
    internetComputerDashboard: null;
} | {
    icpTokensNet: null;
} | {
    coinGecko: null;
} | {
    coinMarketCap: null;
} {
    return value == ApiSource.internetComputerDashboard ? {
        internetComputerDashboard: null
    } : value == ApiSource.icpTokensNet ? {
        icpTokensNet: null
    } : value == ApiSource.coinGecko ? {
        coinGecko: null
    } : value == ApiSource.coinMarketCap ? {
        coinMarketCap: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApiStatus): {
    pending: null;
} | {
    error: null;
} | {
    success: null;
} {
    return value == ApiStatus.pending ? {
        pending: null
    } : value == ApiStatus.error ? {
        error: null
    } : value == ApiStatus.success ? {
        success: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChartTimeframe): {
    fourHours: null;
} | {
    oneHour: null;
} | {
    sevenDays: null;
} | {
    oneYear: null;
} | {
    eightHours: null;
} | {
    fifteenMinutes: null;
} | {
    oneMonth: null;
} | {
    oneDay: null;
} {
    return value == ChartTimeframe.fourHours ? {
        fourHours: null
    } : value == ChartTimeframe.oneHour ? {
        oneHour: null
    } : value == ChartTimeframe.sevenDays ? {
        sevenDays: null
    } : value == ChartTimeframe.oneYear ? {
        oneYear: null
    } : value == ChartTimeframe.eightHours ? {
        eightHours: null
    } : value == ChartTimeframe.fifteenMinutes ? {
        fifteenMinutes: null
    } : value == ChartTimeframe.oneMonth ? {
        oneMonth: null
    } : value == ChartTimeframe.oneDay ? {
        oneDay: null
    } : value;
}
function to_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PriceSourceData>): Array<_PriceSourceData> {
    return value.map((x)=>to_candid_PriceSourceData_n51(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OrderBookEntry>): Array<_OrderBookEntry> {
    return value.map((x)=>to_candid_OrderBookEntry_n54(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
